name: Crawl dictionary sitemap

on:
  pull_request:
  schedule:
    - cron:  '0 0 0 1,15 *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Crawl Dictionary sitemap
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn start
      env:
        CI: true